services:
  backend:
    build:
      context: ./backend
    image: biswalswaraj88/thesius-app:backend
    env_file:
      - ./.env
    volumes:
      - ./backend/:/app
      - ../thesius.db:/app/thesius.db
    expose:
      - "8000"
    depends_on:
      - redis
      - mongodb
    restart: always

  frontend:
    build:
      context: ./frontend
    image: biswalswaraj88/thesius-app:frontend
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
    expose:
      - "3000"
    restart: always
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-stack-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ../mongoDB:/data/db
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    restart: always
