services:
  backend:
    image: biswalswaraj88/thesius-app:backend
    env_file:
      - ./.env
    volumes:
      - ./backend/:/app  # Bind-mount local code
      - ../thesius.db:/app/thesius.db
      - /app/node_modules  # Prevent overriding node_modules in the container
    expose:
      - "8000"
    depends_on:
      - redis
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8000  # Enable hot reload
    restart: always

  frontend:
    image: biswalswaraj88/thesius-app:frontend
    env_file:
      - ./.env
    volumes:
      - ./frontend/:/app  # Bind-mount local code
      - /app/node_modules  # Prevent overriding node_modules in the container
    expose:
      - "3000"
    command: npm run dev  # Run dev server for hot reload
    restart: always
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-stack-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ../mongoDB:/data/db
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    restart: always
